price_data = {
  "Fresh Water Fish": [
    { "title": "Rahu Fish (Rohu)", "price":  790 },
    { "title": "Silver Carp (Silver)", "price": 590 },
    { "title": "Common Carp (Gulfam)", "price": 790 },
    { "title": "Tilapia (Daiyya)", "price": 770 },
    { "title": "Catla Fish (Catla)", "price": 680 },
    { "title": "Wallago Fish (Malli)", "price": 820 },
  ],
  "Crabs & Lobsters": [
    { "title": "Mud Crab (Kekra)", "price": 1090  },
    { "title": "Three Spot Crab (Tikkari)", "price": 900 },
    { "title": "Blue Swimmer Crab (Nela Kekra)", "price": 1200 },
    { "title": "Slipper Lobster (Jangli Kikat)", "price": 2850 },
    { "title": "Lobster (Kikat)", "price": 3700 },
  ],
 "Prawns": [
    { "title": "Large Prawns", "price": 1470 },
    { "title": "Medium Prawns", "price": 1290 },
    { "title": "Small Prawns", "price": 950 },
    { "title": "Jumbo Prawns", "price": 2190 },
    { "title": "Tiger Prawns (Tiger Jheenga)", "price": 3290 },
    { "title": "Tiger Prawns (Tiger Jheenga) Full Size", "price":  3990},
  ],
  "Boneless": [
    { "title": "Queen Fish (Saram) Boneless", "price": 1690 },
    { "title": "Lemon Sole (Boneless)", "price": 1660 },
    { "title": "Tuna (Dawan) Boneless", "price": 1970 },
    { "title": "Mahi Mahi (Amroos) Boneless", "price":  1790 },
    { "title": "Indian Salmon (Rawans) Boneless", "price": 3690 },
    { "title": "Tripletail (Dai) Boneless", "price":  2820 },
    { "title": "Halibut (Hajjam) Boneless", "price":   2190 },
    { "title": "Bhetki (Daangri) Boneless", "price": 4225 },
  ],
  "Squids": [
    { "title": "Cuttlefish (Cuttle)", "price": 1690 },
    { "title": "Squids (Maiyya)", "price":  1540 },
    { "title": "Octopus (Pichangra)", "price":  1900 },
  ],
  "Sea Fish": [
    { "title": "King Fish (Surmai)", "price": 1790 },
    { "title": "Lemon Sole (Sole)", "price":  880 },
    { "title": "Red Snapper (Heera)", "price":  1690 },
    { "title": "Indian Salmon (Rawans)", "price": 1520 },
    { "title": "Bengal Corvina (Goli Mushka)", "price":  1390 },
    { "title": "Bhetki (Daangri)", "price":  1690 },
    { "title": "White Pomfret (Safaid Paplet)", "price": 1990 },
    { "title": "Grouper (Ghissar)", "price":  1570 },
    { "title": "Halibut (Hajjam)", "price":  1220  },
    { "title": "Catfish (Khagga)", "price": 670 },
    { "title": "Mahi Mahi (Amloshk)", "price":  890 },
    { "title": "Tuna (Dawan)", "price":  890 },
    { "title": "Croaker (Mushka)", "price": 790 },
    { "title": "Tripletail (Dai)", "price":  1190 },
    { "title": "Seabream (Safaid Dandia)", "price":  920 },
    { "title": "Black Pomfret (Kala Paplet)", "price": 850 },
    { "title": "White Barracuda (Safaid Kund)", "price": 1490 },
    { "title": "Leather Jacket Fish (Irani Paplet)", "price":  1150 },
    { "title": "Mullet Fish (Boi)", "price": 830 },
    { "title": "Javelin Grunter (Dhotar)", "price":   1490 },
    { "title": "Goldsilk Bream (Kala Dandia)", "price":  890 },
    { "title": "Scat Fish (Kui)", "price": 590 },
    { "title": "Bridled Bream (Captain)", "price":  840 },
    { "title": "Reef Cod (Daama)", "price":  890 },
    { "title": "Drepane (Jalebi)", "price": 730 },
    { "title": "Diamond Trevally (Pattal)", "price":  930 },
    { "title": "Black Barracuda (Kala Kund)", "price":  830 },
    { "title": "Pompano (Sonaf)", "price": 1020 },
    { "title": "Lady Fish (Bhambore)", "price":  1290 },    
    { "title": "Indian Mackerel (Bangda)", "price":  770 },
    { "title": "Giant Trevally (Kakkar)", "price": 830 },
    { "title": "Goldline Bream (Kapartan)", "price":  740 },    
    { "title": "Flathead (Kukkar)", "price":  920  },  
    { "title": "Emperor Fish (Mulla)", "price": 1290 },   
    { "title": "Cobia Fish (Sangra)", "price":  1290 }, 
    { "title": "Amberjack (Saafi)", "price":  950 },
  ]
}